#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN3PAPIFILES =	papiAttributeListAddValue.3papi		\
	 	papiJobSubmit.3papi			\
	 	papiLibrarySupportedCall.3papi		\
	 	papiPrintersList.3papi			\
	 	papiServiceCreate.3papi			\
	 	papiStatusString.3papi

include ../Makefile.man
