#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy is of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN3SYSEVENTFILES =	sysevent_bind_handle.3sysevent		\
	 	 	sysevent_free.3sysevent			\
	 	 	sysevent_get_attr_list.3sysevent	\
	 	 	sysevent_get_class_name.3sysevent	\
	 	 	sysevent_get_vendor_name.3sysevent	\
	 	 	sysevent_post_event.3sysevent		\
	 	 	sysevent_subscribe_event.3sysevent

include ../Makefile.man
