#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy is of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN3LAYOUTFILES = 	m_create_layout.3layout		\
	 	 	m_destroy_layout.3layout	\
	 	 	m_getvalues_layout.3layout	\
	 	 	m_setvalues_layout.3layout	\
	 	 	m_transform_layout.3layout	\
	 	 	m_wtransform_layout.3layout

include ../Makefile.man
