#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN3RESOLVFILES = resolver.3resolv

MAN3RESOLVSOFILES =	dn_comp.3resolv		\
	 	dn_expand.3resolv		\
	 	fp_resstat.3resolv		\
	 	herror.3resolv			\
	 	hstrerror.3resolv		\
	 	res_getservers.3resolv		\
	 	res_hostalias.3resolv		\
	 	res_init.3resolv		\
	 	res_mkquery.3resolv		\
	 	res_nclose.3resolv		\
	 	res_ndestroy.3resolv		\
	 	res_ninit.3resolv		\
	 	res_nmkquery.3resolv		\
	 	res_nquery.3resolv		\
	 	res_nquerydomain.3resolv	\
	 	res_nsearch.3resolv		\
	 	res_nsend.3resolv		\
	 	res_nsendsigned.3resolv		\
	 	res_query.3resolv		\
	 	res_search.3resolv		\
	 	res_send.3resolv		\
	 	res_setservers.3resolv

MAN3RESOLVFILES += $(MAN3RESOLVSOFILES)

dn_comp.3resolv			:= SOSRC = man3resolv/resolver.3resolv
dn_expand.3resolv		:= SOSRC = man3resolv/resolver.3resolv
fp_resstat.3resolv		:= SOSRC = man3resolv/resolver.3resolv
herror.3resolv			:= SOSRC = man3resolv/resolver.3resolv
hstrerror.3resolv		:= SOSRC = man3resolv/resolver.3resolv
res_getservers.3resolv		:= SOSRC = man3resolv/resolver.3resolv
res_hostalias.3resolv		:= SOSRC = man3resolv/resolver.3resolv
res_init.3resolv		:= SOSRC = man3resolv/resolver.3resolv
res_mkquery.3resolv		:= SOSRC = man3resolv/resolver.3resolv
res_nclose.3resolv		:= SOSRC = man3resolv/resolver.3resolv
res_ndestroy.3resolv		:= SOSRC = man3resolv/resolver.3resolv
res_ninit.3resolv		:= SOSRC = man3resolv/resolver.3resolv
res_nmkquery.3resolv		:= SOSRC = man3resolv/resolver.3resolv
res_nquery.3resolv		:= SOSRC = man3resolv/resolver.3resolv
res_nquerydomain.3resolv	:= SOSRC = man3resolv/resolver.3resolv
res_nsearch.3resolv		:= SOSRC = man3resolv/resolver.3resolv
res_nsend.3resolv		:= SOSRC = man3resolv/resolver.3resolv
res_nsendsigned.3resolv		:= SOSRC = man3resolv/resolver.3resolv
res_query.3resolv		:= SOSRC = man3resolv/resolver.3resolv
res_search.3resolv		:= SOSRC = man3resolv/resolver.3resolv
res_send.3resolv		:= SOSRC = man3resolv/resolver.3resolv
res_setservers.3resolv		:= SOSRC = man3resolv/resolver.3resolv

include ../Makefile.man
