#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy is of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN3KVMFILES = 	kvm_getu.3kvm		\
	 	kvm_kread.3kvm		\
	 	kvm_nextproc.3kvm	\
	 	kvm_nlist.3kvm		\
	 	kvm_open.3kvm		\
	 	kvm_read.3kvm

include ../Makefile.man
