#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN5FILES = 	Intro.5			\
	 	acl.5			\
	 	ad.5			\
	 	ascii.5			\
	 	attributes.5		\
	 	audit_binfile.5		\
	 	audit_remote.5		\
	 	audit_syslog.5		\
	 	brands.5		\
	 	cancellation.5		\
	 	charmap.5		\
	 	condition.5		\
	 	crypt_bsdbf.5		\
	 	crypt_bsdmd5.5		\
	 	crypt_sha256.5		\
	 	crypt_sha512.5		\
	 	crypt_sunmd5.5		\
	 	crypt_unix.5		\
	 	device_clean.5		\
	 	dhcp.5			\
	 	dhcp_modules.5		\
	 	environ.5		\
	 	eqnchar.5		\
	 	extendedFILE.5		\
	 	filesystem.5		\
	 	fnmatch.5		\
	 	formats.5		\
	 	fsattr.5		\
	 	grub.5			\
	 	gss_auth_rules.5	\
	 	hal.5			\
	 	iconv.5			\
	 	iconv_unicode.5		\
	 	ieee802.11.5		\
	 	ipfilter.5		\
	 	isalist.5		\
	 	kerberos.5		\
	 	krb5_auth_rules.5	\
	 	krb5envvar.5		\
	 	largefile.5		\
	 	lf64.5			\
	 	lfcompile.5		\
	 	lfcompile64.5		\
	 	locale.5		\
	 	man.5			\
	 	mansun.5		\
	 	me.5			\
	 	mech_spnego.5		\
	 	mm.5			\
	 	ms.5			\
	 	mutex.5			\
	 	nfssec.5		\
	 	pam_allow.5		\
	 	pam_authtok_check.5	\
	 	pam_authtok_get.5	\
	 	pam_authtok_store.5	\
	 	pam_deny.5		\
	 	pam_dhkeys.5		\
	 	pam_dial_auth.5		\
	 	pam_krb5.5		\
	 	pam_krb5_migrate.5	\
	 	pam_ldap.5		\
	 	pam_list.5		\
	 	pam_passwd_auth.5	\
	 	pam_rhosts_auth.5	\
	 	pam_roles.5		\
	 	pam_sample.5		\
	 	pam_smb_passwd.5	\
	 	pam_smbfs_login.5	\
	 	pam_tsol_account.5	\
	 	pam_unix_account.5	\
	 	pam_unix_auth.5		\
	 	pam_unix_cred.5		\
	 	pam_unix_session.5	\
	 	pkcs11_kernel.5		\
	 	pkcs11_softtoken.5	\
	 	pkcs11_tpm.5		\
	 	privileges.5		\
	 	prof.5			\
	 	rbac.5			\
	 	regex.5			\
	 	regexp.5		\
	 	resource_controls.5	\
	 	smf.5			\
	 	smf_bootstrap.5		\
	 	smf_method.5		\
	 	smf_restarter.5		\
	 	smf_security.5		\
	 	smf_template.5		\
	 	standards.5		\
	 	sticky.5		\
	 	tecla.5			\
	 	term.5			\
	 	threads.5		\
	 	trusted_extensions.5	\
	 	vgrindefs.5		\
	 	zones.5

include ../Makefile.man
