#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy is of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN3MALLOCFILES = 	bsdmalloc.3malloc		\
	 	 	malloc.3malloc			\
	 	 	mapmalloc.3malloc		\
	 	 	mtmalloc.3malloc		\
	 	 	umem_alloc.3malloc		\
	 	 	umem_cache_create.3malloc	\
	 	 	umem_debug.3malloc		\
	 	 	watchmalloc.3malloc

include ../Makefile.man
