#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy is of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN3PERLFILES =	Exacct.3perl			\
	 	Exacct\:\:Catalog.3perl		\
	 	Exacct\:\:File.3perl		\
	 	Exacct\:\:Object.3perl		\
	 	Exacct\:\:Object\:\:Group.3perl \
	 	Exacct\:\:Object\:\:Item.3perl	\
	 	Kstat.3perl			\
	 	Lgrp.3perl			\
	 	Privilege.3perl			\
	 	Project.3perl			\
	 	Task.3perl			\
	 	Ucred.3perl

include ../Makefile.man
