#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN9PFILES = 	ddi-forceattach.9p		\
	 	inquiry-device-type.9p		\
	 	no-involuntary-power-cycles.9p	\
	 	pm-components.9p		\
	 	pm.9p				\
	 	removable-media.9p		\
	 	size.9p

include ../Makefile.man
