#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Copyright (c) 2011 Bayard G. Bell. All rights reserved.
#

UTSBASE = ../..
UTSMACH = intel
include $(SRC)/uts/intel/io/amr/Makefile.com
