#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN3PLOTFILES = plot.3plot

MAN3PLOTSOFILES =	arc.3plot	\
		 	box.3plot	\
		 	circle.3plot	\
		 	closepl.3plot	\
		 	closevt.3plot	\
		 	cont.3plot	\
		 	erase.3plot	\
		 	label.3plot	\
		 	line.3plot	\
		 	linemod.3plot	\
		 	move.3plot	\
		 	openpl.3plot	\
		 	openvt.3plot	\
		 	point.3plot	\
		 	space.3plot

MAN3PLOTFILES += $(MAN3PLOTSOFILES)

arc.3plot	:= SOSRC = man3plot/plot.3plot
box.3plot	:= SOSRC = man3plot/plot.3plot
circle.3plot	:= SOSRC = man3plot/plot.3plot
closepl.3plot	:= SOSRC = man3plot/plot.3plot
closevt.3plot	:= SOSRC = man3plot/plot.3plot
cont.3plot	:= SOSRC = man3plot/plot.3plot
erase.3plot	:= SOSRC = man3plot/plot.3plot
label.3plot	:= SOSRC = man3plot/plot.3plot
line.3plot	:= SOSRC = man3plot/plot.3plot
linemod.3plot	:= SOSRC = man3plot/plot.3plot
move.3plot	:= SOSRC = man3plot/plot.3plot
openpl.3plot	:= SOSRC = man3plot/plot.3plot
openvt.3plot	:= SOSRC = man3plot/plot.3plot
point.3plot	:= SOSRC = man3plot/plot.3plot
space.3plot	:= SOSRC = man3plot/plot.3plot


include ../Makefile.man
