#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy is of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN1CFILES = 	ct.1c		\
		cu.1c		\
		rup.1c		\
		uucp.1c		\
		uuencode.1c	\
		uuglist.1c	\
		uustat.1c	\
		uuto.1c		\
		uux.1c		\

include ../Makefile.man
