#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy is of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN1FFILES = 	coproc.1f	\
	 	echo.1f		\
	 	fmlcut.1f	\
	 	fmlexpr.1f	\
	 	fmlgrep.1f	\
	 	getfrm.1f	\
	 	getitems.1f	\
	 	indicator.1f	\
	 	message.1f	\
	 	pathconv.1f	\
	 	readfile.1f	\
	 	regex.1f	\
	 	reinit.1f	\
	 	reset.1f	\
	 	run.1f		\
	 	set.1f		\
	 	setcolor.1f	\
	 	shell.1f	\
	 	test.1f		\
	 	vsig.1f		\

include ../Makefile.man
