#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2024 Oxide Computer Company
#

#
# This contains a number of non-destructive tests that require a
# specific NVMe device to target. This must be invoked by the top-level
# scripts which will validate that the selected device is usable.
#
# Tests that involve optional device-specific behavior such as the persistent
# event log tests are not included as part of this to ensure that this test
# remains working on the broadest set of devices.
#

[DEFAULT]
pre =
verbose = False
quiet = False
timeout = 120
post =
outputdir = /var/tmp/test_results

[/opt/nvme-tests/tests/ioctl/bad-lock.32]
user = root
arch = i86pc

[/opt/nvme-tests/tests/ioctl/bad-lock.64]
user = root

[/opt/nvme-tests/tests/ioctl/basic-get-feature.32]
user = root
arch = i86pc

[/opt/nvme-tests/tests/ioctl/basic-get-feature.64]
user = root

[/opt/nvme-tests/tests/ioctl/basic-get-log.32]
user = root
arch = i86pc

[/opt/nvme-tests/tests/ioctl/basic-get-log.64]
user = root

[/opt/nvme-tests/tests/ioctl/basic-identify.32]
user = root
arch = i86pc

[/opt/nvme-tests/tests/ioctl/basic-identify.64]
user = root

[/opt/nvme-tests/tests/ioctl/basic-lock.32]
user = root
arch = i86pc

[/opt/nvme-tests/tests/ioctl/basic-lock.64]
user = root

[/opt/nvme-tests/tests/ioctl/ctrl-block-lock.32]
user = root
arch = i86pc

[/opt/nvme-tests/tests/ioctl/ctrl-block-lock.64]
user = root

[/opt/nvme-tests/tests/ioctl/lock-order.32]
user = root
arch = i86pc

[/opt/nvme-tests/tests/ioctl/lock-order.64]
user = root

[/opt/nvme-tests/tests/ioctl/lock-signal.32]
user = root
arch = i86pc

[/opt/nvme-tests/tests/ioctl/lock-signal.64]
user = root

[/opt/nvme-tests/tests/ioctl/multi-lock-err.32]
user = root
arch = i86pc

[/opt/nvme-tests/tests/ioctl/multi-lock-err.64]
user = root

[/opt/nvme-tests/tests/ioctl/multi-reader-lock.32]
user = root
arch = i86pc

[/opt/nvme-tests/tests/ioctl/multi-reader-lock.64]
user = root

[/opt/nvme-tests/tests/libnvme/bad-req.32]
user = root
arch = i86pc

[/opt/nvme-tests/tests/libnvme/bad-req.64]
user = root

[/opt/nvme-tests/tests/libnvme/ctrl-disc.32]
user = root
arch = i86pc

[/opt/nvme-tests/tests/libnvme/ctrl-disc.64]
user = root

[/opt/nvme-tests/tests/libnvme/info-roundtrip.32]
user = root
arch = i86pc

[/opt/nvme-tests/tests/libnvme/info-roundtrip.64]
user = root

[/opt/nvme-tests/tests/libnvme/missing-field.32]
user = root
arch = i86pc

[/opt/nvme-tests/tests/libnvme/missing-field.64]
user = root

[/opt/nvme-tests/tests/libnvme/ns-disc.32]
user = root
arch = i86pc

[/opt/nvme-tests/tests/libnvme/ns-disc.64]
user = root

[/opt/nvme-tests/tests/libnvme/ns-info.32]
user = root
arch = i86pc

[/opt/nvme-tests/tests/libnvme/ns-info.64]
user = root

[/opt/nvme-tests/tests/nvmeadm]
user = root
tests = [
	'nvmeadm_test'
	]
