#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2025 Oxide Computer Company
#

#
# This contains a number of non-destructive tests that require a
# specific NVMe device to target. This must be invoked by the top-level
# scripts which will validate that the selected device is usable.
#

[DEFAULT]
pre =
verbose = False
quiet = False
timeout = 120
post =
outputdir = /var/tmp/test_results

[/opt/nvme-tests/tests/unit/32/]
arch = i86pc
tests = [
	'feature.32',
	'firmware.32',
	'format.32',
	'identify.32',
	'logs.32',
	'nsmgmt.32',
	'version.32',
	'vuc.32',
	]

[/opt/nvme-tests/tests/unit/64/]
tests = [
	'feature.64',
	'firmware.64',
	'format.64',
	'identify.64',
	'logs.64',
	'nsmgmt.64',
	'version.64',
	'vuc.64',
	]

[/opt/nvme-tests/tests/libnvme/32/sctostr.32]
arch = i86pc

[/opt/nvme-tests/tests/libnvme/64/sctostr.64]
