#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN3TNFFILES = 	TNF_DECLARE_RECORD.3tnf		\
	 	TNF_PROBE.3tnf			\
	 	libtnfctl.3tnf			\
	 	tnf_process_disable.3tnf	\
	 	tnfctl_buffer_alloc.3tnf	\
	 	tnfctl_close.3tnf		\
	 	tnfctl_indirect_open.3tnf	\
	 	tnfctl_internal_open.3tnf	\
	 	tnfctl_kernel_open.3tnf		\
	 	tnfctl_pid_open.3tnf		\
	 	tnfctl_probe_apply.3tnf		\
	 	tnfctl_probe_state_get.3tnf	\
	 	tnfctl_register_funcs.3tnf	\
	 	tnfctl_strerror.3tnf		\
	 	tnfctl_trace_attrs_get.3tnf	\
	 	tnfctl_trace_state_set.3tnf	\
	 	tracing.3tnf

include ../Makefile.man
