#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2026 Michael van der Westhuizen
#

MODULE = pcibus
ARCH = armv8
CLASS = arch
UTILDIR = ../../../common/pcibus
HBDIR = ../../../common/hostbridge
NICDIR = ../../../common/nic
USBDIR = ../../../common/usb
UFMDIR = ../../../common/ufm
SHAREDDIR = ../../../common/shared
UTILSRCS = did.c did_hash.c did_props.c util.c
PCISRCS = pcibus.c pcibus_labels.c pcibus_hba.c pci_sensor.c
SHAREDSRCS = topo_sensor.c

MODULESRCS = $(UTILSRCS) $(PCISRCS) pci_armv8.c

include ../../../Makefile.plugin

LDLIBS += -ldevinfo -lsmbios -lpcidb

CPPFLAGS += -I$(UTILDIR) -I$(HBDIR) -I$(NICDIR) -I$(USBDIR) -I$(SHAREDDIR)
CPPFLAGS += -I$(UFMDIR)

%.o: $(SHAREDDIR)/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)
