#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Garrett D'Amore <garrett@damore.org>
# Copyright 2019 Joyent, Inc.
# Copyright 2022 OmniOS Community Edition (OmniOSce) Association.
# Copyright 2023 Bill Sommerfeld <sommerfeld@alum.mit.edu>
# Copyright 2026 Oxide Computer Company
#

[DEFAULT]
pre =
verbose = False
quiet = False
timeout = 120
post =
outputdir = /var/tmp/test_results

[/opt/libc-tests/tests/fexecve_test]
[/opt/libc-tests/tests/fpround_test]
[/opt/libc-tests/tests/newlocale_test]
[/opt/libc-tests/tests/nl_langinfo_test]
[/opt/libc-tests/tests/wcsrtombs_test]
[/opt/libc-tests/tests/wctype_test]

[/opt/libc-tests/tests/32]
arch = i86pc
tests = [
	'ascftime.32',
	'asprintf-14933.32',
	'c11_threads.32',
	'c11_tss.32',
	'call_once.32',
	'clock_lock.32',
	'closefrom.32',
	'dprintf.32',
	'endian.32',
	'env-7076.32',
	'fnmatch.32',
	'getlocname.32',
	'isatty.32',
	'localeconv.32',
	'memchr.32',
	'memset_s.32',
	'mutex-16200.32',
	'mutex_attr.32',
	'posix_memalign.32',
	'printf-15294.32',
	'printf-9511.32',
	'ptsname.32',
	'set_constraint_handler_s.32',
	'stdbit.32',
	'strcoll-strxfrm-6907.32',
	'strerror.32',
	'strtonum.32',
	'strtox.32',
	'swprintf-17781.32',
	'timespec_get.32',
	'timespec_getres.32',
	'uchar.32',
	'utimes.32',
	'wcsftime.32',
	'wcsftime_old.32',
	'wcslcat.32',
	'wcslcpy.32',
	'wcsncasecmp-7344.32',
	'wcsncasecmp-7350.32',
	'wcsncasecmp.32',
	]

[/opt/libc-tests/tests/64]
tests = [
	'ascftime.64',
	'asprintf-14933.64',
	'c11_threads.64',
	'c11_tss.64',
	'call_once.64',
	'clock_lock.64',
	'closefrom.64',
	'dprintf.64',
	'endian.64',
	'env-7076.64',
	'fnmatch.64',
	'getlocname.64',
	'isatty.64',
	'localeconv.64',
	'memchr.64',
	'memset_s.64',
	'mutex-16200.64',
	'mutex_attr.64',
	'posix_memalign.64',
	'printf-15294.64',
	'printf-9511.64',
	'ptsname.64',
	'set_constraint_handler_s.64',
	'stdbit.64',
	'strcoll-strxfrm-6907.64',
	'strerror.64',
	'strtonum.64',
	'strtox.64',
	'swprintf-17781.64',
	'timespec_get.64',
	'timespec_getres.64',
	'uchar.64',
	'utimes.64',
	'wcsftime.64',
	'wcsftime_old.64',
	'wcslcat.64',
	'wcslcpy.64',
	'wcsncasecmp-7344.64',
	'wcsncasecmp-7350.64',
	'wcsncasecmp.64',
	]

[/opt/libc-tests/tests/i18n/bindtextdomain_test]
[/opt/libc-tests/tests/qsort/qsort_test]

[/opt/libc-tests/tests/random/getrandom]
[/opt/libc-tests/tests/random/getentropy]
[/opt/libc-tests/tests/random/chacha]
[/opt/libc-tests/tests/random/inz_child]
[/opt/libc-tests/tests/random/inz_inval]
#
# root privs required for mlock privileges
#
[/opt/libc-tests/tests/random/inz_mlock]
user = root
[/opt/libc-tests/tests/random/inz_region]
[/opt/libc-tests/tests/random/inz_split]
[/opt/libc-tests/tests/random/inz_split_vpp]
[/opt/libc-tests/tests/random/inz_vpp]
[/opt/libc-tests/tests/random/arc4random]
[/opt/libc-tests/tests/random/arc4random_fork]
[/opt/libc-tests/tests/random/arc4random_prefork]
[/opt/libc-tests/tests/random/arc4random_forkall]
[/opt/libc-tests/tests/random/arc4random_preforkall]
[/opt/libc-tests/tests/random/arc4random_forksig]
[/opt/libc-tests/tests/random/arc4random_preforksig]
#
# root privs required for DTrace
#
[/opt/libc-tests/tests/random/arc4key.ksh]
user = root

[/opt/libc-tests/tests/regex/regex_test]

[/opt/libc-tests/tests/select/select.sh]
timeout = 600

[/opt/libc-tests/tests/stdio/32/]
arch = i86pc
tests = [
	'fdclose.32',
	'fileno.32',
	'fmemopentest.32',
	'ftell_ungetc.32',
	'ftello_12768.32',
	'ftello_12768.lfs',
	'memstream.32',
	'memstream_reopen.32',
	'open_memstreamtest.32',
	'orientation_test.32',
	'test_mbrtowc.32'
	]

[/opt/libc-tests/tests/stdio/64/]
tests = [
	'fdclose.64',
	'fileno.64',
	'fmemopentest.64',
	'ftell_ungetc.64',
	'ftello_12768.64',
	'memstream.64',
	'memstream_reopen.64',
	'open_memstreamtest.64',
	'orientation_test.64',
	'test_mbrtowc.64'
	]

[/opt/libc-tests/tests/aligned_alloc]
[/opt/libc-tests/tests/catopen]
[/opt/libc-tests/tests/err/err.ksh]

[/opt/libc-tests/tests/posix_spawn/32]
arch = i86pc
tests = [
	'posix_spawn_attr.32',
	'posix_spawn_chdir.32',
	'posix_spawn_fileactions.32',
	'posix_spawn_path.32',
	'posix_spawn_pipe_np.32',
	]

[/opt/libc-tests/tests/posix_spawn/64]
tests = [
	'posix_spawn_attr.64',
	'posix_spawn_chdir.64',
	'posix_spawn_fileactions.64',
	'posix_spawn_path.64',
	'posix_spawn_pipe_np.64'
	]

[/opt/libc-tests/tests/posix_spawn/32/posix_spawn_priv.32]
arch = i86pc
user = root

[/opt/libc-tests/tests/posix_spawn/64/posix_spawn_priv.64]
user = root

[/opt/libc-tests/tests/64/printf-6961.64]
[/opt/libc-tests/tests/printf-intmax]
[/opt/libc-tests/tests/priv_gettext]
[/opt/libc-tests/tests/psignal]
[/opt/libc-tests/tests/quick_exit]
[/opt/libc-tests/tests/thread_name]

#
# root privs required for priority changes
#
[/opt/libc-tests/tests/pthread_attr_get_np]
user=root

[/opt/libc-tests/tests/symbols]
pre = setup
tests = [
	'assert_h',
	'ctype_h',
	'dirent_h',
	'fcntl_h',
	'locale_h',
	'math_h',
	'netdb_h',
	'pthread_h',
	'signal_h',
	'stdalign_h',
	'stddef_h',
	'stdio_h',
	'stdlib_h',
	'stdnoreturn_h',
	'string_h',
	'strings_h',
	'sys_atomic_h',
	'sys_mman_h',
	'sys_stat_h',
	'sys_time_h',
	'sys_timeb_h',
	'time_h',
	'threads_h',
	'ucontext_h',
	'unistd_h',
	'wchar_h',
	'wctype_h'
	 ]
timeout = 180
