#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy is of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN3XTSOLFILES = 	XTSOLIsWindowTrusted.3xtsol		\
	 	 	XTSOLMakeTPWindow.3xtsol		\
	 	 	XTSOLgetClientAttributes.3xtsol		\
	 	 	XTSOLgetPropAttributes.3xtsol		\
	 	 	XTSOLgetPropLabel.3xtsol		\
	 	 	XTSOLgetPropUID.3xtsol			\
	 	 	XTSOLgetResAttributes.3xtsol		\
	 	 	XTSOLgetResLabel.3xtsol			\
	 	 	XTSOLgetResUID.3xtsol			\
	 	 	XTSOLgetSSHeight.3xtsol			\
	 	 	XTSOLgetWorkstationOwner.3xtsol		\
	 	 	XTSOLsetPolyInstInfo.3xtsol		\
	 	 	XTSOLsetPropLabel.3xtsol		\
	 	 	XTSOLsetPropUID.3xtsol			\
	 	 	XTSOLsetResLabel.3xtsol			\
	 	 	XTSOLsetResUID.3xtsol			\
	 	 	XTSOLsetSSHeight.3xtsol			\
	 	 	XTSOLsetSessionHI.3xtsol		\
	 	 	XTSOLsetSessionLO.3xtsol		\
	 	 	XTSOLsetWorkstationOwner.3xtsol

include ../Makefile.man
