#

#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Copyright (c) 2011 Bayard G. Bell. All rights reserved.
# Copyright (c) 2018, Joyent, Inc.
#

UTSBASE = ../..
UTSMACH = intel
include $(SRC)/uts/common/gssapi/Makefile.com
