#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2017 Hayashi Naoyuki
# Copyright 2025 Michael van der Westhuizen
#

CORE_OBJS_FDT +=		\
	prom_emul_fdt.o

CORE_OBJS +=			\
	aarch64_subr.o		\
	ddi_aarch64.o		\
	kdi_asm.o		\
	kdi_exceptions.o	\
	kdi_util.o		\
	lock_prim.o		\
	copy.o			\
	mem_config_stubs.o	\
	mem_config_arch.o	\
	memnode.o		\
	lgrpplat.o		\
	hat_aarch64.o		\
	hat_kdi.o		\
	hat_kpm.o		\
	hment.o			\
	htable.o		\
	vm_machdep.o		\
	aarch64_mmu.o		\
	ddi_impl.o		\
	avintr.o		\
	exceptions.o		\
	swtch.o			\
	syspic.o		\
	intr.o			\
	machdep.o		\
	trap.o			\
	mp_machdep.o		\
	mp_startup.o		\
	startup.o		\
	hardclk.o		\
	confunix.o		\
	mach_kdi.o		\
	cpupm.o			\
	cpupm_mach.o		\
	mlsetup.o		\
	ppage.o			\
	dtrace_subr.o		\
	mach_sysconfig.o	\
	fakebop.o		\
	cpc_subr.o		\
	ibft.o			\
	mp_call.o		\
	cbe.o			\
	locore.o		\
	notes.o			\
	hold_page.o		\
	ssp.o			\
	psci.o			\
	arch_timer.o		\
	earlybsa.o		\
	cpuinfo.o

CORE_OBJS += $(PCI_STRING_OBJS)

#
#	Add the SMBIOS subsystem object files directly to the list of objects
#	built into unix itself; this is all common code except for smb_dev.c.
#
CORE_OBJS += $(SMBIOS_OBJS)

#
# These get compiled twice:
# - once in the dboot (direct boot) identity mapped code
# - once for use during early startup in unix
#
BOOT_DRIVER_OBJS =		\
	boot_console.o		\
	boot_fb.o		\
	boot_keyboard.o		\
	boot_psci.o		\
	boot_services.o		\
	boot_uart.o		\
	$(FONT_OBJS)

CORE_OBJS += $(BOOT_DRIVER_OBJS)

DBOOT_OBJS +=			\
	dboot_srt0.o		\
	dboot_self_reloc.o	\
	dboot_main.o		\
	dboot_aarch64_subr.o	\
	dboot_printf.o		\
	dboot_conf.o		\
	dboot_conf_acpi.o	\
	dboot_conf_fdt.o	\
	dboot_conf_uefi.o	\
	dboot_memlist.o		\
	dboot_psci.o		\
	dboot_uefimem.o		\
	dboot_standalloc.o	\
	dboot_standalone.o	\
	dboot_machdep_efi.o	\
	dboot_heap_kmem.o	\
	dboot_machdep.o		\
	dboot_elf_loader.o	\
	dboot_bootflags.o	\
	fdt.o                   \
	fdt_ro.o                \
	fdt_wip.o               \
	fdt_sw.o                \
	fdt_rw.o                \
	fdt_strerror.o          \
	fdt_empty_tree.o        \
	fdt_addresses.o         \
	fdt_overlay.o           \
	fdt_check.o		\
	getoptstr.o		\
	bitext.o		\
	bzero.o			\
	string.o		\
	strtoul.o		\
	memchr.o		\
	memcpy.o		\
	memmove.o		\
	memcmp.o		\
	memset.o		\
	memlist.o		\
	standalloc.o		\
	$(BOOT_DRIVER_OBJS)

PLATMOD_OBJS = platmod.o

SIMPLEBUS_OBJS += simple-bus.o

ROOTNEX_OBJS += rootnex.o

NS16550A_OBJS += ns16550a.o

ARM_GTMR_OBJS += arm_gtmr.o
GICTWO_OBJS += gictwo.o
GICTHREE_OBJS += gicthree.o

PL03ONE_OBJS += pl03one.o

# XXXPCI: Resurrect gfxp_pci.o when we're ready
GFX_PRIVATE_OBJS	+= gfx_private.o gfxp_segmap.o \
			   gfxp_devmap.o gfxp_vm.o \
			   gfxp_fb.o gfxp_bitmap.o

EFIFB_OBJS		+= efifb.o

BOOTDEV_OBJS		+= bootdev.o

ASSYM_DEPS +=			\
	aarch64_subr.o		\
	copy.o			\
	exceptions.o		\
	kdi_asm.o		\
	kdi_exceptions.o	\
	lock_prim.o		\
	locore.o		\
	swtch.o			\
	vpanic.o
