#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Copyright (c) 2018, Joyent, Inc.
#

UTSBASE = ../..
UTSMACH = intel
include $(SRC)/uts/intel/io/acpica/Makefile.com
