#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN3TECLAFILES = 	cpl_complete_word.3tecla		\
	 	 	ef_expand_file.3tecla			\
	 	 	gl_get_line.3tecla			\
	 	 	gl_io_mode.3tecla			\
	 	 	libtecla_version.3tecla			\
	 	 	pca_lookup_file.3tecla

include ../Makefile.man
