#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2020 Joyent, Inc.
# Copyright 2022 OmniOS Community Edition (OmniOSce) Association.
# Copyright 2021 Tintri by DDN, Inc. All rights reserved.
# Copyright 2026 Oxide Computer Company
# Copyright 2022 MNX Cloud, Inc.
#

[DEFAULT]
pre =
verbose = False
quiet = False
timeout = 60
post =
outputdir = /var/tmp/test_results

[/opt/os-tests/tests]
user = root
tests = ['poll_test', 'epoll_test']

[/opt/os-tests/tests/32]
arch = i86pc
tests = [
	'eventfd.32',
	'odirectory.32',
	'clock_gettime.32',
	'statvfs.32',
	'syncfs.32',
	'ucontext.32',
	'getcontext_extd.32',
	'writev.32'
	]

[/opt/os-tests/tests/64]
tests = [
	'eventfd.64',
	'odirectory.64',
	'clock_gettime.64',
	'statvfs.64',
	'syncfs.64',
	'ucontext.64',
	'getcontext_extd.64',
	'writev.64'
	]

[/opt/os-tests/tests/secflags]
user = root
tests = ['secflags_aslr',
         'secflags_core',
         'secflags_dts',
         'secflags_elfdump',
         'secflags_forbidnullmap',
         'secflags_limits',
         'secflags_noexecstack',
         'secflags_proc',
         'secflags_psecflags',
         'secflags_syscall',
         'secflags_truss',
         'secflags_zonecfg']

[/opt/os-tests/tests/signalfd]
tests = ['basic_args', 'basic_read', 'multipoll']

[/opt/os-tests/tests/sigqueue]
tests = ['sigqueue_queue_size']

[/opt/os-tests/tests/sdevfs]
user = root
tests = ['sdevfs_eisdir']

[/opt/os-tests/tests/stress]
user = root
tests = ['dladm-kstat']

[/opt/os-tests/tests/timer]
user = root
tests = ['timer_limit']

[/opt/os-tests/tests/file-locking/32/runtests.32]
arch = i86pc

[/opt/os-tests/tests/file-locking/64/runtests.64]

[/opt/os-tests/tests/sockfs]
user = root
tests = ['conn',
         'dgram',
         'drop_priv',
         'nosignal',
         'so_protocol',
         'sockpair',
	 ]

[/opt/os-tests/tests/sockfs/32]
arch = i86pc
user = root
tests = [
	'recvmsg.32',
	'rights.32',
        'timeouts.32',
	]

[/opt/os-tests/tests/sockfs/64]
user = root
tests = [
	'recvmsg.64',
	'rights.64',
        'timeouts.64',
	]

[/opt/os-tests/tests/syscall/32]
arch = i86pc
tests = ['fchmodat.32', 'open.32']

[/opt/os-tests/tests/syscall/64]
tests = ['fchmodat.64', 'open.64']

[/opt/os-tests/tests/pf_key]
user = root
timeout = 180
tests = ['acquire-compare', 'kmc-update', '15146']

[/opt/os-tests/tests/ddi_ufm]
user = root
tests = ['ufm-test-setup', 'ufm-test', 'ufm-test-cleanup']

[/opt/os-tests/tests/definit/definit]

[/opt/os-tests/tests/idmap/32/idmaptest.32]
arch = i86pc
pre_user=root
pre = /opt/os-tests/tests/idmap/idmap_init
post_user=root
post = /opt/os-tests/tests/idmap/idmap_fini

[/opt/os-tests/tests/idmap/64/idmaptest.64]
pre_user=root
pre = /opt/os-tests/tests/idmap/idmap_init
post_user=root
post = /opt/os-tests/tests/idmap/idmap_fini

[/opt/os-tests/tests/ksid/32/ksid.32]
arch = i86pc

[/opt/os-tests/tests/ksid/64/ksid.64]

[/opt/os-tests/tests/i386]
user = root
arch = i86pc
timeout = 300
tests = ['ldt', 'badseg']

[/opt/os-tests/tests/imc_test]
arch = i86pc

#
# Except atrparse all tests require special hardware (CCID YubiKey) to run,
# hence they aren't included in the default runfile.
#
[/opt/os-tests/tests/uccid]
arch = i86pc
tests = ['atrparse']

[/opt/os-tests/tests/libtopo]
user = root
tests = ['digraph-test']

#
# The GPIO tests require privileges.
#
[/opt/os-tests/tests/gpio/gpioadm_test]
pre_user = root
user = root
post_user = root
pre = /opt/os-tests/tests/gpio/gpio_init
post = /opt/os-tests/tests/gpio/gpio_fini

[/opt/os-tests/tests/gpio/32]
arch = i86pc
pre_user = root
user = root
post_user = root
pre = /opt/os-tests/tests/gpio/gpio_init
post = /opt/os-tests/tests/gpio/gpio_fini
tests = [
	'dpio_test.32',
	'gpio_attr.32',
	'gpio_lookup.32'
	]

[/opt/os-tests/tests/gpio/64]
pre_user = root
user = root
post_user = root
pre = /opt/os-tests/tests/gpio/gpio_init
post = /opt/os-tests/tests/gpio/gpio_fini
tests = [
	'dpio_test.64',
	'gpio_attr.64',
	'gpio_lookup.64'
	]

#
# Only the ksensor functional tests are included in the run file.
# The stress test is designed to be run separately.
#
[/opt/os-tests/tests/ksensor/32]
arch = i86pc
pre_user = root
user = root
post_user = root
pre = /opt/os-tests/tests/ksensor/ksensor_init
tests = [ 'ksensor_basic.32', 'ksensor_err.32' ]
post = /opt/os-tests/tests/ksensor/ksensor_fini

[/opt/os-tests/tests/ksensor/64]
pre_user = root
user = root
post_user = root
pre = /opt/os-tests/tests/ksensor/ksensor_init
tests = [ 'ksensor_basic.64', 'ksensor_err.64' ]
post = /opt/os-tests/tests/ksensor/ksensor_fini

[/opt/os-tests/tests/stackalign/32/stackalign.32]
arch = i86pc

[/opt/os-tests/tests/stackalign/64/stackalign.64]

[/opt/os-tests/tests/cores]
user = root
pre = core_prereqs
tests = ['coretests']

[/opt/os-tests/tests/zen_umc_test]
arch = i86pc

[/opt/os-tests/tests/portfs/32/file_assoc.32]
arch = i86pc

[/opt/os-tests/tests/portfs/64/file_assoc.64]

[/opt/os-tests/tests/regression]
tests = [
	'illumos-15031',
	'illumos-15036'
	]

#
# The following tests all represent tests that require the xsave feature
# set. These are all x86 specific. The use of arch=i86pc below doesn't
# really represent things that can be run on x86 regardless of the
# platform and when the test runner gains support for specifying that,
# use that instead. This would be split into two groups, but that isn't
# supported, so everything ends up being run as root for the sake of the
# xsave_baducontext test.
#
[/opt/os-tests/tests/xsave]
arch = i86pc
pre = xsu_hwtype.64
user = root
tests = [ 'bad_xregs.32', 'bad_xregs.64', 'mdb_xregs', 'proc_writes',
    'setcontext_replace.32', 'setcontext_replace.64', 'setcontext_restore.32',
    'setcontext_restore.64', 'signal_restore.32', 'signal_restore.64',
    'xregs_roundtrip.32', 'xregs_roundtrip.64', 'xsave_baducontext',
    'fpregs_xbv.32', 'fpregs_xbv.64', 'swapcontext_extd.32',
    'swapcontext_extd.64' ]

[/opt/os-tests/tests/hexdump/32/hexdump_basic.32]
arch = i86pc

[/opt/os-tests/tests/hexdump/64/hexdump_basic.64]

[/opt/os-tests/tests/ilstr/32/ilstr_basic.32]
arch = i86pc

[/opt/os-tests/tests/ilstr/64/ilstr_basic.64]

[/opt/os-tests/tests/execvpe/32/execvpe-test.32]
arch = i86pc

[/opt/os-tests/tests/execvpe/64/execvpe-test.64]

[/opt/os-tests/tests/minttl]
user = root
tests = ['minttl', 'minttl_err']

[/opt/os-tests/tests/tcpsig]
pre_user = root
post_user = root
pre = tcpsig_init
tests = ['tcpsig']
post = tcpsig_fini

[/opt/os-tests/tests/32/fifo-tvnsec.32]
arch = i86pc

[/opt/os-tests/tests/64/fifo-tvnsec.64]

[/opt/os-tests/tests/saveargs/functional/functional]
arch = i86pc

[/opt/os-tests/tests/saveargs/testmatch/testmatch]
arch = i86pc

[/opt/os-tests/tests/oclo]
tests = ['oclo', 'oclo_errors']

[/opt/os-tests/tests/secure_getenv/secure_getenv]
user = root

[/opt/os-tests/tests/mac]
user = root
tests = ['mac_parsing', 'mac_ktest']

[/opt/os-tests/tests/ktest]
user = root
tests = ['stream_ktest', 'ktest_ktest']

[/opt/os-tests/tests/comm_page]
user = root
pre = comm_page_pre
tests = ['comm_page_ktest']

[/opt/os-tests/tests/libsocket/32]
arch = i86pc
tests = [
	'getifaddrs_dl.32',
	'inet6_opt.32',
	'nametoindex.32'
	]

[/opt/os-tests/tests/libsocket/64]
tests = [
	'getifaddrs_dl.64',
	'inet6_opt.64',
	'nametoindex.64'
	]
