#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy is of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN9EFILES = 	Intro.9e		\
	 	_fini.9e		\
	 	aread.9e		\
	 	attach.9e		\
	 	awrite.9e		\
	 	chpoll.9e		\
	 	close.9e		\
	 	csx_event_handler.9e	\
	 	detach.9e		\
	 	devmap.9e		\
	 	devmap_access.9e	\
	 	devmap_contextmgt.9e	\
	 	devmap_dup.9e		\
	 	devmap_map.9e		\
	 	devmap_unmap.9e		\
	 	dump.9e			\
	 	getinfo.9e		\
	 	gld.9e			\
	 	identify.9e		\
	 	ioctl.9e		\
	 	ks_snapshot.9e		\
	 	ks_update.9e		\
	 	mmap.9e			\
	 	open.9e			\
	 	power.9e		\
	 	print.9e		\
	 	probe.9e		\
	 	prop_op.9e		\
	 	put.9e			\
	 	quiesce.9e		\
	 	read.9e			\
	 	segmap.9e		\
	 	srv.9e			\
	 	strategy.9e		\
	 	tran_abort.9e		\
	 	tran_bus_reset.9e	\
	 	tran_dmafree.9e		\
	 	tran_getcap.9e		\
	 	tran_init_pkt.9e	\
	 	tran_quiesce.9e		\
	 	tran_reset.9e		\
	 	tran_reset_notify.9e	\
	 	tran_setup_pkt.9e	\
	 	tran_start.9e		\
	 	tran_sync_pkt.9e	\
	 	tran_tgt_free.9e	\
	 	tran_tgt_init.9e	\
	 	tran_tgt_probe.9e	\
	 	write.9e

include ../Makefile.man
