#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy is of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN3SLPFILES = 	SLPClose.3slp			\
	 	SLPDelAttrs.3slp		\
	 	SLPDereg.3slp			\
	 	SLPEscape.3slp			\
	 	SLPFindAttrs.3slp		\
	 	SLPFindScopes.3slp		\
	 	SLPFindSrvTypes.3slp		\
	 	SLPFindSrvs.3slp		\
	 	SLPFree.3slp			\
	 	SLPGetProperty.3slp		\
	 	SLPGetRefreshInterval.3slp	\
	 	SLPOpen.3slp			\
	 	SLPParseSrvURL.3slp		\
	 	SLPReg.3slp			\
	 	SLPSetProperty.3slp		\
	 	SLPUnescape.3slp		\
	 	slp_api.3slp			\
	 	slp_strerror.3slp

include ../Makefile.man
