#

#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Copyright 2019, Joyent, Inc.
#

UTSBASE = ../..
UTSMACH = aarch64
include $(SRC)/uts/common/exec/elf/Makefile.com
