#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# uts/armv8/rpi4/Makefile.files
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Copyright 2017 Hayashi Naoyuki
# Copyright 2025 Michael van der Westhuizen
#

#
#	Global definitions for rpi4 implementation specific modules.
#

#
#	Define objects.
#

# bcm2711 drivers
BCM2711_EMMCTWO_OBJS	+= bcm2711_emmctwo.o
BCM2711_GENET_OBJS	+= bcm2711_genet.o
BCM2711_SENSORS_OBJS	+= bcm2711_sensors.o

# Raspberry Pi 4 platform module
RPI4_PLATMOD_OBJS	= bcm2835_mbox.o rpi4.o

#
#	include rpi4 header files
#
INC_PATH	+= -I$(UTSBASE)/armv8 -I$(UTSBASE)/armv8/rpi4
