#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy is of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN7MFILES = 	bufmod.7m	\
	 	connld.7m	\
	 	kb.7m		\
	 	ldterm.7m	\
	 	pckt.7m		\
	 	pfmod.7m	\
	 	pipemod.7m	\
	 	ptem.7m		\
	 	sppptun.7m	\
	 	timod.7m	\
	 	tirdwr.7m	\
	 	ttcompat.7m	\
	 	usb_ah.7m	\
	 	usbkbm.7m	\
	 	usbms.7m	\
	 	vuidmice.7m

include ../Makefile.man
