#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy is of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN3VOLMGTFILES = 	media_findname.3volmgt		\
	 	 	media_getattr.3volmgt		\
	 	 	media_getid.3volmgt		\
	 	 	volmgt_acquire.3volmgt		\
	 	 	volmgt_check.3volmgt		\
	 	 	volmgt_feature_enabled.3volmgt	\
	 	 	volmgt_inuse.3volmgt		\
	 	 	volmgt_ownspath.3volmgt		\
	 	 	volmgt_release.3volmgt		\
	 	 	volmgt_root.3volmgt		\
	 	 	volmgt_running.3volmgt		\
	 	 	volmgt_symname.3volmgt

include ../Makefile.man
