#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy is of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2010, Richard Lowe

include ../../Makefile.master

MAN3SECFILES = 	acl_check.3sec		\
	 	acl_free.3sec		\
	 	acl_get.3sec		\
	 	acl_strip.3sec		\
	 	acl_totext.3sec		\
	 	acl_trivial.3sec	\
	 	aclcheck.3sec		\
	 	aclsort.3sec		\
	 	acltomode.3sec		\
	 	acltotext.3sec

include ../Makefile.man
